service: newrelic-lambda-layers-python-example

provider:
  name: aws
  stage: prod
  region: us-east-1
  stackTags:
    environment: us-testing
    owning_team: LAMBDA
    product: aws-lambda
  tags:
    environment: us-testing
    owning_team: LAMBDA
    product: aws-lambda

plugins:
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}
    apiKey: ${env:NEW_RELIC_PERSONAL_API_KEY}
    debug: true

functions:
  layer-python36:
    events:
      - schedule: rate(5 minutes)
    handler: handler.handler
    package:
      exclude:
        - ./**
      include:
        - handler.py
    runtime: python3.6

  layer-python37:
    events:
      - schedule: rate(5 minutes)
    handler: handler.handler
    package:
      exclude:
        - ./**
      include:
        - handler.py
    runtime: python3.7

  layer-python38:
    events:
      - schedule: rate(5 minutes)
    handler: handler.handler
    package:
      exclude:
        - ./**
      include:
        - handler.py
    runtime: python3.8

  layer-python39:
    events:
      - schedule: rate(5 minutes)
    handler: handler.handler
    package:
      exclude:
        - ./**
      include:
        - handler.py
    runtime: python3.9
