service: newrelic-lambda-layers-nodejs-example

provider:
  name: aws
  stage: prod
  region: us-east-1

plugins:
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}
    debug: true

functions:
  layer-nodejs810:
    events:
      - schedule: rate(5 minutes)
    handler: handler.handler
    package:
      exclude:
        - ./**
      include:
        - handler.js
    runtime: nodejs8.10

  layer-nodejs10x:
    events:
      - schedule: rate(5 minutes)
    handler: handler.handler
    package:
      exclude:
        - ./**
      include:
        - handler.js
    runtime: nodejs10.x
